### ISSUE TITLE
Problem running Kubernetes demo (5_demo)

### ISSUE THREAD

**Issue by talrom** [ballerina-guides/ballerina-demo#14]
**Description:**
After building the project from the .bal file I'm getting the k8s deployment, service and config yaml.
when deploying on a k8s cluster pod fails to start.

I suspect this is relate to the docker image:
@kubernetes:Deployment {
 image: "demo/ballerina-demo",
 name: "ballerina-demo"
}

Thanks!

**Comment by lakwarus** [comment]
What is your environment ? Are you using docker-for-mac-edge or minikube? If your k8s cluster is not running with local docker registry, then either you have to connect to docker remote registry (which your k8s cluster can access) or have to push into docker registry that can pull from the k8s cluster.

Special Note for minikube users on ubuntu: You need to add the minikube host and certs path under "Deployment" annotation.
@kubernetes:Deployment {
    image: "demo/ballerina-demo",
    name: "ballerina-demo",
    dockerHost:"tcp://192.168.99.100:2376", 
    dockerCertPath:"/home/chanaka/.minikube/certs"
}

**Comment by anupama-pathirage** [comment]
Closing as we no longer maintain this repo.
