### ISSUE TITLE
Shouldn't ask to create .ballerina folder

### ISSUE THREAD

**Issue by nirmal070125** [ballerina-guides/ballerina-demo#29]
**Description:**

In the README, there's a statement saying "Create two folders in it: .ballerina and demo ". I don't think we need to ask users to create .ballerina folder;
   1. as none of the steps in the demo using ballerina project concept
   2. `ballerina init` is there if we are to initiate a ballerina project.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Closing as we no longer maintain this repo.
